version: "2.6"

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: product
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
      - "5432:5432"
    volumes:
          - ./data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./ddl/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
          # copy the sql script to fill tables
          - ./ddl/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    container_name: db_container
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    links:
      - "db"
    ports:
      - "80:8080"
    container_name: etl_container
    depends_on:
      - db
    stdin_open: true
    tty: true